[tool.poetry]
name = "mysfa"
version = "1.0.0"
description = "営業成果共有に特化したWebアプリケーション"
authors = ["森岡大智 <karumuwairo@gmail.com>"]
readme = "README.md"
packages = [{include = "mysfa", from = "src"}, {include = "config", from = "src"}, {include = "accounts", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
Django = ">=5.0,<5.1"
mysqlclient = ">=2.0"
whitenoise = "*"
python-dotenv = "*"
gunicorn = "*"
Pillow = "*"
django-storages = {extras = ["boto3"], version = ">=1.14.4"}
boto3 = ">=1.34.0"

[tool.poetry.group.dev.dependencies]
flake8 = ">=6.0.0"
black = ">=23.3.0"
isort = ">=5.12.0"
pytest = ">=7.0.0"
pytest-django = ">=4.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py312"]
include = '\.pyi?$'
extend-exclude = '''
/(
  migrations
  | staticfiles
  | media
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_django = "django"
known_first_party = ["accounts", "mysfa", "config"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["mysfa", "config", "accounts"]
