# Generated by Django 3.2 on 2024-08-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0002_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.ImageField(blank=True, default='default_images/702.png', upload_to='group_icon_path'),
        ),
    ]
