# Generated by Django 3.2 on 2024-08-18 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snsapp', '0003_group_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='custom_id',
            field=models.CharField(blank=True, default='00000000', max_length=8, unique=True, verbose_name='グループID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(blank=True, default='default_images/702.png', upload_to='group_icon_path', verbose_name='グループアイコン'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='グループメンバー'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(verbose_name='投稿文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='post',
            name='customer_category',
            field=models.CharField(error_messages={'blank': '顧客カテゴリを入力してください'}, max_length=50, verbose_name='顧客カテゴリ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='product_name',
            field=models.CharField(error_messages={'blank': '商品名を入力してください'}, max_length=50, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
    ]
