# Generated by Django 3.2 on 2024-09-04 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth import get_user_model

User = get_user_model()

def set_default_creator(apps, schema_editor):
    Group = apps.get_model('snsapp', 'Group')
    for group in Group.objects.all():
        first_user = group.users.first()
        if first_user:
            group.creator = first_user
            group.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snsapp', '0006_auto_20240828_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='グループ作成者'),
        ),
        migrations.RunPython(set_default_creator),
    ]
