# Generated by Django 3.2 on 2024-09-11 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snsapp', '0007_group_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_approval',
            field=models.BooleanField(default=False, verbose_name='承認機能'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='ロック機能'),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='依頼日時')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snsapp.group', verbose_name='グループ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='依頼ユーザー')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
