# Generated by Django 5.0.14 on 2025-12-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysfa", "0005_post_liked_users"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
