# Generated by Django 5.0.14 on 2026-01-03 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysfa", "0006_delete_mymodel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="有効フラグ"),
        ),
        migrations.AlterField(
            model_name="group",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="グループ作成者",
            ),
        ),
    ]
