# Generated by Django 5.0.14 on 2026-01-09 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysfa", "0007_group_is_active_alter_group_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry_code",
                    models.CharField(max_length=50, verbose_name="業態コード"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="業態名")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_masters",
                        to="mysfa.group",
                        verbose_name="グループ",
                    ),
                ),
            ],
            options={
                "ordering": ["group_id", "industry_code"],
            },
        ),
        migrations.CreateModel(
            name="ProductMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="商品コード"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="商品名")),
                (
                    "category_main",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="大分類"
                    ),
                ),
                (
                    "category_sub",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="小分類"
                    ),
                ),
                (
                    "cost_price",
                    models.IntegerField(blank=True, null=True, verbose_name="商品原価"),
                ),
                (
                    "price_excl_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="販売価格（税抜）",
                    ),
                ),
                (
                    "price_incl_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="販売価格（税込）",
                    ),
                ),
                (
                    "custom_text_1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="自由項目（文字1）",
                    ),
                ),
                (
                    "custom_text_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="自由項目（文字2）",
                    ),
                ),
                (
                    "custom_text_3",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="自由項目（文字3）",
                    ),
                ),
                (
                    "custom_int_1",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="自由項目（数値1）"
                    ),
                ),
                (
                    "custom_int_2",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="自由項目（数値2）"
                    ),
                ),
                (
                    "custom_date_1",
                    models.DateField(
                        blank=True, null=True, verbose_name="自由項目（日付1）"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="自由記入"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_masters",
                        to="mysfa.group",
                        verbose_name="グループ",
                    ),
                ),
            ],
            options={
                "ordering": ["group_id", "product_code"],
            },
        ),
        migrations.AddConstraint(
            model_name="industrymaster",
            constraint=models.UniqueConstraint(
                fields=("group", "industry_code"),
                name="uq_industrymaster_group_industry_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmaster",
            constraint=models.UniqueConstraint(
                fields=("group", "product_code"),
                name="uq_productmaster_group_product_code",
            ),
        ),
    ]
