# Generated by Django 5.0.14 on 2026-01-12 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysfa", "0008_industrymaster_productmaster_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="industrymaster",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="有効フラグ"),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="有効フラグ"),
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("PRODUCT", "商品"), ("INDUSTRY", "業態")],
                        max_length=20,
                        verbose_name="種別",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "下書き"),
                            ("PENDING", "承認待ち"),
                            ("APPROVED", "承認済み(反映済み)"),
                            ("REJECTED", "却下"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="タイトル"
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="メモ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="依頼日時"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認/却下日時"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_requests_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="mysfa.group",
                        verbose_name="対象グループ",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="依頼者",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeRequestRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_index",
                    models.PositiveIntegerField(verbose_name="行番号(1始まり)"),
                ),
                (
                    "op",
                    models.CharField(
                        choices=[("UPSERT", "追加/更新"), ("DELETE", "削除")],
                        max_length=10,
                        verbose_name="操作",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="コード")),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="名称"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="取込可能"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="エラーコード",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", verbose_name="エラーメッセージ"
                    ),
                ),
                (
                    "diff_json",
                    models.JSONField(blank=True, null=True, verbose_name="差分(JSON)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="mysfa.changerequest",
                        verbose_name="変更依頼",
                    ),
                ),
            ],
            options={
                "ordering": ["row_index"],
            },
        ),
        migrations.AddIndex(
            model_name="changerequest",
            index=models.Index(
                fields=["group", "kind", "status"],
                name="mysfa_chang_group_i_cf3c9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="changerequest",
            index=models.Index(
                fields=["group", "created_at"], name="mysfa_chang_group_i_b893f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="changerequestrow",
            index=models.Index(
                fields=["change_request", "is_valid"],
                name="mysfa_chang_change__588abd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="changerequestrow",
            index=models.Index(
                fields=["change_request", "code"], name="mysfa_chang_change__75d2cf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="changerequestrow",
            constraint=models.UniqueConstraint(
                fields=("change_request", "row_index"),
                name="uq_change_request_row_change_request_row_index",
            ),
        ),
    ]
