# Generated by Django 5.0.14 on 2026-01-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysfa", "0009_industrymaster_is_active_productmaster_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmaster",
            name="cost_price",
        ),
        migrations.RemoveField(
            model_name="productmaster",
            name="price_excl_tax",
        ),
        migrations.RemoveField(
            model_name="productmaster",
            name="price_incl_tax",
        ),
    ]


