# Generated by Django 5.0.14 on 2026-01-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysfa", "0010_remove_productmaster_prices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="industrymaster",
            options={"ordering": ["group_id", "name", "id"]},
        ),
        migrations.RemoveConstraint(
            model_name="industrymaster",
            name="uq_industrymaster_group_industry_code",
        ),
        migrations.RemoveField(
            model_name="industrymaster",
            name="industry_code",
        ),
        migrations.AddConstraint(
            model_name="industrymaster",
            constraint=models.UniqueConstraint(
                fields=("group", "name"), name="uq_industrymaster_group_name"
            ),
        ),
    ]
