# Generated by Django 5.0.14 on 2026-01-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysfa", "0011_alter_industrymaster_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="customer_category",
        ),
        migrations.RemoveField(
            model_name="post",
            name="product_name",
        ),
        migrations.AddField(
            model_name="post",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="mysfa.industrymaster",
                verbose_name="業態",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="mysfa.productmaster",
                verbose_name="商品",
            ),
        ),
    ]
