# Generated by Django 5.0.14 on 2026-01-21 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysfa", "0012_remove_post_customer_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequest",
            name="trial_session_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="トライアルセッションID",
            ),
        ),
        migrations.AddField(
            model_name="changerequestrow",
            name="trial_session_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="トライアルセッションID",
            ),
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="trial_session_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="トライアルセッションID",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="trial_session_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="トライアルセッションID",
            ),
        ),
        migrations.AddIndex(
            model_name="changerequest",
            index=models.Index(
                fields=["trial_session_id"], name="mysfa_chang_trial_s_f95987_idx"
            ),
        ),
    ]
