# Generated by Django 5.0.14 on 2026-01-26 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysfa", "0015_create_postcomment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="postcomment",
            new_name="mysfa_postc_post_id_6bcd6f_idx",
            old_name="mysfa_postc_post_id_1c2d4a_idx",
        ),
        migrations.RenameIndex(
            model_name="postcomment",
            new_name="mysfa_postc_parent__424f3c_idx",
            old_name="mysfa_postc_parent__8b7d91_idx",
        ),
    ]
