# Generated by Django 5.0.14 on 2026-01-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysfa", "0017_create_groupmembership"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="groupmembership",
            new_name="mysfa_group_group_i_8cc3db_idx",
            old_name="idx_gm_group_role_active",
        ),
        migrations.RenameIndex(
            model_name="groupmembership",
            new_name="mysfa_group_user_id_5c7f98_idx",
            old_name="idx_gm_user_active",
        ),
    ]
