# Generated by Django 5.0.14 on 2026-02-11 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mysfa",
            "0018_rename_idx_gm_group_role_active_mysfa_group_group_i_8cc3db_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
