# Generated by GPT on 2026-02-11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysfa", "0019_alter_post_options_alter_group_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS mysfa_group_users;",
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="group",
                    name="users",
                    field=models.ManyToManyField(
                        related_name="user_groups",
                        through="mysfa.GroupMembership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="グループメンバー",
                    ),
                )
            ],
        ),
    ]

