# Generated by Django 3.2 on 2024-08-16 16:54

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('custom_user_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]+$', message='userIDは半角英数字のみ使用できます。')])),
                ('password1', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(?=.*[0-9])(?=.*[a-zA-Z]).{5,15}$', message='パスワードは半角英数字を各1文字以上含む5文字以上15文字以下で入力してください。')])),
                ('password2', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(?=.*[0-9])(?=.*[a-zA-Z]).{5,15}$', message='パスワードは半角英数字を各1文字以上含む5文字以上15文字以下で入力してください。')])),
                ('question', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(blank=True, default='default_images/ic013.png', upload_to=accounts.models.CustomUser.user_profile_image_path)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
