# Generated by Django 3.2 on 2024-08-18 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='answer',
            field=models.CharField(max_length=20, verbose_name='答え'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='custom_user_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]+$', message='userIDは半角英数字のみ使用できます。')], verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password1',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(?=.*[0-9])(?=.*[a-zA-Z]).{5,15}$', message='パスワードは半角英数字を各1文字以上含む5文字以上15文字以下で入力してください。')], verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password2',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(?=.*[0-9])(?=.*[a-zA-Z]).{5,15}$', message='パスワードは半角英数字を各1文字以上含む5文字以上15文字以下で入力してください。')], verbose_name='パスワード確認'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='question',
            field=models.CharField(max_length=20, verbose_name='秘密の質問'),
        ),
    ]
