# Generated by Django 3.2 on 2024-09-08 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240818_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='answer',
            field=models.CharField(max_length=128, verbose_name='答え'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password1',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*[0-9])(?=.*[a-zA-Z]).{5,15}$', message='パスワードは半角英数字を各1文字以上含む5文字以上15文字以下で入力してください。')], verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password2',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^(?=.*[0-9])(?=.*[a-zA-Z]).{5,15}$', message='パスワードは半角英数字を各1文字以上含む5文字以上15文字以下で入力してください。')], verbose_name='パスワード確認'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='question',
            field=models.CharField(max_length=128, verbose_name='秘密の質問'),
        ),
    ]
