# Generated by Django 5.0.14 on 2025-12-25 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password1",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?=.*[0-9])(?=.*[a-zA-Z]).{5,20}$",
                        message="パスワードは半角英数字を各1文字以上含む5文字以上20文字以下で入力してください。",
                    )
                ],
                verbose_name="パスワード",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password2",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?=.*[0-9])(?=.*[a-zA-Z]).{5,20}$",
                        message="パスワードは半角英数字を各1文字以上含む5文字以上20文字以下で入力してください。",
                    )
                ],
                verbose_name="パスワード確認",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="question",
            field=models.CharField(max_length=20, verbose_name="秘密の質問"),
        ),
    ]
