# Generated by Django 5.0.14 on 2025-12-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_password1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="password1",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="password2",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=20),
        ),
    ]
