# Generated by GPT on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_customuser_password1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_trial",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="trial_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="trial_expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="trial_session_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]

